### ISSUE TITLE
[karma][v4.0]app failed to open

### ISSUE THREAD

**Issue by 44asad** [YahiaAngelo/Karma#2]
### Actual behavior

App crashing again and again ,can not open the app.
### Expected behavior

Expected that i can open the app and can use successfully
### How to reproduce
* Install the apps and open the app
* Use app sometimes
* Minimize the app and clear the app from recent used app.
* Now try to open the app again.
* Do 2-4 steps again.
* See the bug
### Information
App version:v4.0
OS:Android 6.0.1
Device:Samsung j5
### Recording Of The Bug
https://youtu.be/ftOvakxnYEc

### logcat:
<pre><code>05-16 08:55:20.618 18191 18191 E AndroidRuntime: FATAL EXCEPTION: main
05-16 08:55:20.618 18191 18191 E AndroidRuntime: Process: com.angelo.karma, PID: 18191
05-16 08:55:20.618 18191 18191 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.angelo.karma/com.angelo.karma.LoginActivity}: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3352)
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   at android.app.ActivityThread.access$1100(ActivityThread.java:223)
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1797)
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:102)
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:158)
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:7231)
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
05-16 08:55:20.618 18191 18191 E AndroidRuntime: Caused by: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   at android.app.ActivityManager$TaskDescription.<init>(ActivityManager.java:641)
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   at android.app.Activity.onApplyThemeResource(Activity.java:4076)
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:150)
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:94)
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   at androidx.appcompat.app.AppCompatActivity.setTheme(AppCompatActivity.java:111)
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   at com.angelo.karma.LoginActivity.onCreate(LoginActivity.java:41)
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   at android.app.Activity.performCreate(Activity.java:6877)
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3209)
05-16 08:55:20.618 18191 18191 E AndroidRuntime:   ... 9 more</code></pre>

**Comment by YahiaAngelo** [comment]
Thanks for reporting.
The problem with opaque colors as primary color in android 6.0 .
I'll fix the issue asap.

**Comment by 44asad** [comment]
ok,thanks you!
